### ISSUE TITLE
Add License Acceptance Option to WebSphere Liberty Operator

### ISSUE THREAD

**Issue by malincoln** [WASdev/websphere-liberty-operator#1]
now that the Operators will be delivered with Liberty/tWAS, we were discussing how the license will be displayed with Alasdair. There will be a pull down choice that will allow the customer to accept the license via WAS, Family Edition, CP4Apps or WHE. This will need to be implemented by the Operators. I think we need issues to track this which I can get opened for both Operators.

Slack discussion: https://ibm-cloud.slack.com/archives/C020VHDP0M8/p1639495015013000

**Comment by leochr** [comment]
[box note with license input for products](https://ibm.ent.box.com/notes/913452659805)
