### ISSUE TITLE
SSL Handshake Error between microservices when manageTLS: true

### ISSUE THREAD

**Issue by danielguinan1** [WASdev/websphere-liberty-operator#118]
I have two microservices deployed using the websphere liberty operator and both have `manageTLS: 'true'` which is the default.  I see the following error when one microservice attempts to access another:
```
[5/5/22 15:05:19:374 UTC] 00000030 SystemOut O Login Failed - check connection to Customer Service.
[5/5/22 15:05:23:606 UTC] 00000043 com.ibm.ws.ssl.core.WSX509TrustManager E CWPKI0823E: SSL HANDSHAKE FAILURE: A signer with SubjectDN [CN=*.<URL>] was sent from the host [<URL>:443]. The signer might need to be added to local trust store [/opt/ol/wlp/output/defaultServer/resources/security/key.p12], located in SSL configuration alias [defaultSSLConfig]. The extended error message from the SSL handshake exception is: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target].
```
I came to know about the following environment variable documented here: https://github.com/OpenLiberty/ci.docker/blob/master/SECURITY.md#tls-certificate-configuration
which resolved this issue when adding to the `WebsphereLibertyApplication` `SEC_IMPORT_K8S_CERTS=true`
My defect is that I believe this should be enabled by default as different microservices in the same namespace deployed by the operator should trust each other by default.

**Comment by mtamboli** [comment]
@danielguinan1 Please verify and close this issue

**Comment by danielguinan1** [comment]
After removing the following lines from the working deployment files I can confirm I am hitting this issue with a previous driver (`icr.io/cpopen/websphere-liberty-operator-catalog@sha256:c2ea165e272f600973b853fcb053b3be75825e9b2d890c0d386124cad28a75b2`).
```
    - name: SEC_IMPORT_K8S_CERTS
      value: 'true'
```
`[5/23/22 13:52:04:753 UTC] 0000004a com.ibm.ws.ssl.core.WSX509TrustManager E CWPKI0823E: SSL HANDSHAKE FAILURE: A signer with SubjectDN [CN=*.apps.pituri.cp.fyre.ibm.com] was sent from the host [acmeair-main-websphere2.apps.ibm.com:443]. The signer might need to be added to local trust store [/opt/ol/wlp/output/defaultServer/resources/security/key.p12], located in SSL configuration alias [defaultSSLConfig]. The extended error message from the SSL handshake exception is: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target].
`
Updating to the latest to see if the problem persists

**Comment by danielguinan1** [comment]
After uninstalling the old driver and installing the latest (`icr.io/cpopen/websphere-liberty-operator-catalog@sha256:1064b5516db14577561ff3930aeffb2f1cf386325bc11e12b3ced9f64c27f9b6`) I can confirm no SSL Handshake Error is occuring.
