### ISSUE TITLE
Update yaml file with manageTLS: True

### ISSUE THREAD

**Issue by mtamboli** [WASdev/websphere-liberty-operator#124]
When an application is deployed using WLO, it sets the `manageTLS: True` but this is not added to yaml file. Since this is a significant configuration, it is best for user to know that TLS is enabled. Also, currently n OCP console provides incorrect status where it seems like that TLS is disabled when it is really enabled. It would be good to have this setting added to yaml by default.

![image](https://user-images.githubusercontent.com/29490950/167486352-b09d6b79-cc10-4a41-8594-94690d2bfc3f.png)

**Comment by leochr** [comment]
`spec.manageTLS` is set to true in the sample CR. 

Resolved by PR https://github.com/WASdev/websphere-liberty-operator/pull/138
