### ISSUE TITLE
Knative Service fails to use the default pull secret

### ISSUE THREAD

**Issue by danielguinan1** [WASdev/websphere-liberty-operator#125]
I'm not sure if this is WLO related, but when attempting to create knative service with the WLO the image fails to pull with the following error:
```
Unable to fetch image "artifactory.swg-devops.com/repo/image:tag": failed to resolve image to digest: GET https://artifactory.swg-devops.com: : Authentication is required
```
The pull policy is set to `Always` and the image pulls perfectly fine when not creating a knative service but will not work with it.  This error also occurs when creating a knative of the default application, and was repeated on a second cluster.

fyi @mtamboli

**Comment by mtamboli** [comment]
Here is the error when using the sample application on OCP 4.10 cluster.

Steps to re-create the problem:
1. Install `Red Hat OpenShift Serverless` operator
2. Create `knative-serving` instance in namespace `knative-serving`
3. Deploy WebSphereLiberty sample app with `createKnativeService: true`

![image](https://user-images.githubusercontent.com/29490950/167512165-413c5f63-c6c8-4e82-b4d6-a6b30182355d.png)

**Comment by mtamboli** [comment]
Is there a way to workaround it from RH? We cannot expect users to copy their images to public repos.

**Comment by BradleyMayo** [comment]
We sometimes use the Openshift private registry insecurely for testing.```
  oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
    oc patch image.config.openshift.io/cluster  --patch '{"spec":{"registrySources":{"insecureRegistries":["'$OCP_REGISTRY_URL'"]}}}' --type=merge
```

Are you able to use something similar to this?

**Comment by leochr** [comment]
@danielguinan1 @mtamboli We'll document the global pull secret limitation for Knative on OCP. Please try with the `.spec.pullSecret` as suggested by Artur. Thanks.

**Comment by danielguinan1** [comment]
I created a pull secret in the same namespace as the application via the openshift console, then referenced that secret with `pullSecret: aa-pull-secret` while having the `pullPolicy: Always` and was able to pull the image without issue.
