### ISSUE TITLE
Add product and cloud pak IDs based on WebSphere edition

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#140]
It turns out that the product ID and cloud pak IDs are based on the edition (core, nd, base) and is not the same as we believed.

Change the operator logic to add license/metric annotations based on the edition. Note: Avoid using the drop-down on the top-left to change the edition. It doesn't actually switch the content, which is what led to this issue. Instead, use these direct links:

Base: https://www.ibm.com/docs/en/was-liberty/base?topic=container-tracking-liberty-usage-in-kubernetes-license-service
Core: https://www.ibm.com/docs/en/was-liberty/core?topic=container-tracking-liberty-usage-in-kubernetes-license-service
ND (Network Deployment): https://www.ibm.com/docs/en/was-liberty/nd?topic=container-tracking-liberty-usage-in-kubernetes-license-service

Relevant code in operator:
[License Editions](https://github.com/WASdev/websphere-liberty-operator/blob/d7584d329d510b17a7ae564d0bc6b1c14966aeba/api/v1/webspherelibertyapplication_types.go#L193)
[Util method that adds annotations](https://github.com/WASdev/websphere-liberty-operator/blob/d7584d329d510b17a7ae564d0bc6b1c14966aeba/utils/utils.go#L176)

**Comment by halim-lee** [comment]
All combinations of product IDs and cloudPak IDs are validated through annotation validation tool: https://readytool.kraklab.pl.ibm.com:9443/ReadyTool/dashboard.xhtml

E.g.
![Base-CP4A](https://user-images.githubusercontent.com/43827333/168346881-b8ec1ea6-66b9-4dfe-a5b3-31e8325d1e4b.png)

![Core-Family](https://user-images.githubusercontent.com/43827333/168346914-a66f8f68-7f6b-4c48-8a1a-fe041c9d4909.png)

![ND-WSHE](https://user-images.githubusercontent.com/43827333/168346944-6d02e787-69c6-4e67-9acc-e62283ae9ea9.png)
