### ISSUE TITLE
No certificate expiration errors in the logs

### ISSUE THREAD

**Issue by jagraj** [WASdev/websphere-liberty-operator#148]
We executed 24hrs stress run with custom certificates for WebSphere liberty application. We configured certificates expiration policy duration "1hr" and renewalBefore  "30mins". We do see that the pods are getting recycled and we are trying to validate in the pod logs if there are any certificate errors and we do not find any. How can we validate if the operator is refreshing the certificates for the WLO app instance.?

**Comment by leochr** [comment]
@jagraj If the certifications are getting renewed before they expire, as they should, then there shouldn't be any certificate errors. New pods would be created when the certificates are refreshed, so you can list the pods every 30 minutes or so. You can also look at the pod creation time if you want to check only the last set of pods.

**Comment by jagraj** [comment]
Thanks for the information, How can I find information from the WLO why the pods are getting recycled.?
Are there any events or logs tell us why application pods are getting recycled.?

**Comment by leochr** [comment]
@jagraj In this scenario, new pods are expected to be created to provide new certs. The Pods are managed by k8s. WLO updates the Deployment as necessary and the operator captures the Deployment reconcile in its logs. But that happens frequently, not just when certs are needed to be updated.

**Comment by jagraj** [comment]
@leochr 
Thanks for the information, based on our conversation looks like cert-manager always keep certs valid and renews them automatically and that is why we do not see certification expiration error messages in the logs.
