### ISSUE TITLE
Assess the SonarQube results

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#151]
The results should be in the Cloud Object Storage (uploaded by the OnePipeline build)

**Comment by mingcyu** [comment]
SonarQube results are available here: http://cp4d-sonarqube.svl.ibm.com:9000/sonar/dashboard?id=websphere-liberty-operator

Login is w3 id

**Comment by mingcyu** [comment]
At the moment the focus is on any code that will cause vulnerabilities or security risks

**Comment by leochr** [comment]
There are no vulnerabilities or security issues reported. 

2 items are identified as 'Bugs' by SonarQube. Both are related to unused variables:
http://cp4d-sonarqube.svl.ibm.com:9000/sonar/project/issues?id=websphere-liberty-operator&resolved=false&types=BUG

**Comment by mingcyu** [comment]
Scan from 5/23 have not changed

**Comment by leochr** [comment]
Scan from June 2nd: There are no vulnerabilities or security issues reported. 

2 new items are reported as 'Bugs' - similar to the others and related to unused variables.
