### ISSUE TITLE
7.1 - Static Image Size

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#16]

**Comment by leochr** [comment]
@idlewis The [Dockerfile for catalog image](https://github.com/WASdev/websphere-liberty-operator/blob/main/index.Dockerfile) is now available. Please evaluate it for these guidelines. Thanks.

**Comment by idlewis** [comment]
@leochr The catalog dockerfile meets all the guidelines, no changes needed

**Comment by idlewis** [comment]
As discussed, it was decided to remove the microdnf update from the catalog image, as this further reduces the images size.
