### ISSUE TITLE
Assess the Twistlock/VA scan results

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#172]

**Comment by idlewis** [comment]
This is the latest scan report
[newcves-report-5_22_2022.11_30_31.PM_wlo_catalog.csv](https://github.com/WASdev/websphere-liberty-operator/files/8770247/newcves-report-5_22_2022.11_30_31.PM_wlo_catalog.csv)

**Comment by idlewis** [comment]
For the CVEs which we inherit from the UBI 8 base image, are all either 'affected' or 'under investigation', none of them are yet 'fixed', so there is no fix available.
There are 3 CVEs in /usr/bin/grpc_health_probe which we copy in to the catalog image from `registry.redhat.io/openshift4/ose-operator-registry:v4.9`
4.10 is available, but it isn't clear if this will have the fixes.

**Comment by mingcyu** [comment]
Updated the Residual Analysis master copy: https://ibm.box.com/s/54ijwix8gj2kljtf8fwik268sjj4o6zu

**Comment by mingcyu** [comment]
No New VA or Twist lock vulnerabilities reported

**Comment by mingcyu** [comment]
Work is completed
