### ISSUE TITLE
Handle k8s resource conflict due to same CR names

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#179]
Both Open Liberty Operator (OLO) and WebSphere Liberty Operator (WLO) create the Kubernetes resources for the application (i.e. Deployment, Service, Route, etc) using the CR name (OpenLibertyApplication for OLO or WebSphereLibertyApplication for WLO). Since there could only be one k8s resource with the same k8s name, both operators would try to create and manage the k8s resources. 

We should gracefully handle this potential name conflict in the operators. One approach:
- If the k8s resource already exists (i.e. Deployment/StatefulSet), look at the owner reference and proceed further only if it's already owned by the same operator, otherwise output a meaningful error about the name conflict and exit

- [x] Delivered to RCO
- [x] Delivered to OLO
- [x] Delivered to WLO

**Comment by leochr** [comment]
Need to deliver to OLO, reopening

**Comment by halim-lee** [comment]
https://github.com/OpenLiberty/open-liberty-operator/pull/384
