### ISSUE TITLE
3.2 - Principle of Least Privilege

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#18]
The following page provides guidelines on [Container Image Security](https://playbook.cloudpaklab.ibm.com/cm/containerimagesecurity/)

**Comment by leochr** [comment]
@idlewis The [Dockerfile for catalog image](https://github.com/WASdev/websphere-liberty-operator/blob/main/index.Dockerfile) is now available. Please evaluate it for these guidelines. Thanks.

**Comment by idlewis** [comment]
@leochr The only thing we don't do here is to allow the user id to be specified via a docker ARG.
That isn't a must from the guidelines, and websphere automation doesn't do this.
Would you like to use an ARG for the user? I'f so, i'll do a PR for it.

**Comment by leochr** [comment]
fyi, we discussed this in the scrum and concluded to add ARG to both catalog image and bundle image - to keep it consistent

**Comment by idlewis** [comment]
and ARG for user has been added to both catalog and bundle dockerfiles by #50
