### ISSUE TITLE
Address the CVEs flagged by whitesource scan

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#208]
Evaluate and address the CVEs flagged by whitesource scan: https://github.ibm.com/websphere-compliance/websphere-liberty-operator-whitesource-scan/issues

Some were marked as 'waiting for fix from vendor' (specifically knative). Check whether the vendor library has picked up the fix(es) and if so update WLO

Related to https://github.com/wasdev/websphere-liberty-operator/issues/51

**Comment by mingcyu** [comment]
At iteration planning, @arturdzm mentioned that the one remaining item can possibly be marked as not affected
