### ISSUE TITLE
Documentation for 1.0.1 release

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#210]
- [x] Add a page for upgrade - similar to [WebSphere Automation](https://www.ibm.com/docs/en/ws-automation?topic=installing-updating-websphere-automation) that covers both network-connected env and air gap. Content related to updating IAF (IBM Automation Foundation) should be excluded. Updating the channel is not required and should be excluded. Keep the content about 'patch updates' and 'manual update strategy`
- [x] Replace all instances of `1.0.0` with `1.0.1` (in the commands) for kubectl-based install option : https://www.ibm.com/docs/en/was-liberty/base?topic=operators-installing-kubernetes-cli
- [x] Add a section on how to upgrade kubectl-based installs. Simply point to the kubectl-based install section
- [x] Request SVT to follow and validate the instructions, especially for the Air gap upgrade

**Comment by leochr** [comment]
fyi @jantley-ibm

**Comment by mingcyu** [comment]
@yongja79 Hi Jason, can you take a look at the first one as part of the upgrade?
