### ISSUE TITLE
Update the Liberty app used in sample CR (manual)

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#213]
Do this for the pre-release for 1.0.1 and just prior to the GM release (to pick up the latest version). Once https://github.com/WASdev/websphere-liberty-operator/issues/214 is implemented to automate this, manual update wouldn't be necessary.

- [ ] Update Liberty sample app with the digest for the latest image. _skopeo inspect_ or _podman inspect_ can be used to get the digest: https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11. 

- [ ] Update the related image in CSV : https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/manifests/bases/ibm-websphere-liberty.clusterserviceversion.yaml#L507

- [ ] Run `make bundle` and check in the CSV changes

**Comment by idlewis** [comment]
The liberty getting started at is already at the latest level, so closing this as no action required.
