### ISSUE TITLE
Update and scan with new CV linter version 3.4.0

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#278]
More info on the upcoming changes to Linter version v3.4.0 (Oct 5):  https://ibm.ent.box.com/s/0bstbl4mqvpxpmtrvzjtv2ze3el8x4w0

- `cv lint operator` which is used in WLO pipeline will be removed in January 2023 
  - use `cv lint olm-bundle` instead (as per the answer from Linter team [here](https://github.ibm.com/IBMPrivateCloud/container-content-roadmap/issues/12912#issuecomment-48820487))
  - i.e. `cv lint olm-bundle --container-tool docker cp.stg.icr.io/cp/websphere-liberty-operator@sha256:xxxx`
- There are some new linter rules
-  some linter rules are updated

**Comment by dtadcox** [comment]
@leochr Just wanted to confirm my understanding here.  We are moving to a binary lint (or maybe its source and binary?).  Based on your example, seems like this will have to occur after operator is built now vs. prior (which is how it works today).

**Comment by leochr** [comment]
@dtadcox Yes, the linter tool should use the built operator image (produced by `containerize` stage in OnePipeline)

**Comment by dtadcox** [comment]
PR: https://github.com/WASdev/websphere-liberty-operator/pull/310

**Comment by leochr** [comment]
Closing as completed. Thanks.
