### ISSUE TITLE
WebSphere Liberty (Sample) Image for Entitled Registry

### ISSUE THREAD

**Issue by malincoln** [WASdev/websphere-liberty-operator#3]
This came up during second UFO review for the new TWO/WLO Operators on Jan 31st and during schedule review on Feb1st
by Alasdair.  Opening issue to track this work for WebSphere Liberty.

**Comment by leochr** [comment]
The specified sample image should not be from Red Hat's registry. Instead, it should be from IBM Container Registry (icr.io). The alternative is to exclude the sample image (don't specify it in the sample snippet).
