### ISSUE TITLE
Review the initial results from static linter scan

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#32]

**Comment by mcurran-us** [comment]
Linter results as of 3/16.  Level of operator code is from 3/15.  Please ignore the entries in blue.  These are CASE related which I will resolve
[linter_results_March_16.txt](https://github.com/WASdev/websphere-liberty-operator/files/8318536/linter_results_March_16.txt)
.

**Comment by mcurran-us** [comment]
Link to an explanation of the Rule:  https://playbook.cloudpaklab.ibm.com/content-verification-linter

**Comment by idlewis** [comment]
The remaining errors from the initial linter scan are:

[ERROR] operators/websphere-liberty-operator: no CRD found in any operator that defines a required spec.license.accept field of type boolean in its openAPIV3Schema (CRDDefinesLicenseProperty)
and
[ERROR] bundle/manifests/websphere-liberty.clusterserviceversion.yaml: expected some spec.customresourcedefinitions.owned[i].specDescriptors[j].path to be "license.accept" (CSVDefinesCRDWithLicenseParameter)
 - handled by issues #24 and #25

[ERROR] bundle/manifests/websphere-liberty.clusterserviceversion.yaml: csv spec.descrption missing sections ["Introduction" "Details" "Prerequisites" "Resources Required" "Installing" "Configuration" "Limitations" "SecurityContextConstraints Requirements"]  (CSVDescriptionHasReadmeSections)
 - handled by issue #30

[ERROR] bundle/manifests/websphere-liberty.clusterserviceversion.yaml: expected spec.customresourcedefinitions.owned[0].description to contain ".*(?i)Documentation[\\s\\S]*(?i)ibm\\.biz" (CSVDefinesCRDWithValidDescription)
 - handled by issue #43

**Comment by mcurran-us** [comment]
Static linter results as of 4/6.  Level of operator code is today, commit 90e4764
[static-lint.txt](https://github.com/WASdev/websphere-liberty-operator/files/8430428/static-lint.txt)
