### ISSUE TITLE
Validate that the correct operator version is installed

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#343]
[Build 719](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/eb70f36d-51a6-44fd-a6f3-54449ae615ec/build-containerize/run-stage?env_id=ibm:yp:us-south) produced a CataloSource image that only had the operator bundles with 1.0.0, 1.0.1 and 1.0.2 but not 1.1.0. The operator installed and tested on the cluster was incorrect.

We should validate:
- [x] that the operator version is correct. We should also update the Subscription to specify startingCSV value.
- [x] that the built image is used in the operator deployment (wlo-controller-manager)

--------------

- [x] Delivered to WLO
- [x] Delivered to OLO
- [x] Delivered to RCO

**Comment by yongja79** [comment]
OLO PR - https://github.com/OpenLiberty/open-liberty-operator/pull/443
RCO PR - https://github.com/application-stacks/runtime-component-operator/pull/555
