### ISSUE TITLE
Share build scripts between WLO, RCO and OLO

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#359]
It'll be ideal to share the build scripts between WLO, RCO and OLO. It'll make it easy to update and maintain them without having to duplicate resources at each operator.

**Comment by halim-lee** [comment]
RCO, OLO and WLO are using shared build scripts in OnePipeline
RCO: https://github.com/application-stacks/runtime-component-operator/pull/485
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/388
WLO: https://github.com/WASdev/websphere-liberty-operator/pull/399
