### ISSUE TITLE
Run acceptance tests in all supported modes

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#365]
The existing WLO/RCO build pipeline provides an option to select only ONE of the install mode. It might be ideal to have an option to run ALL supported modes (AllNamespaces, OwnNamespace, SingleNamespace). Clean up of namespace-level resources (i.e. ConfigMaps) and cluster level resources (CRDs) should be done in between the modes to avoid using artifacts from other install modes.

**Comment by dtadcox** [comment]
@leochr Currently, both RCO and WLO are locked to using `OwnNamespace`.  While there is a build script enumeration option, that value is currently not supported.  So, there will be more work here needed to make this happen.  Additionally, I could use some help identifying the artifacts that will need to be cleaned up between runs.  Do we have any current examples of how to make this happen?  I guess a full `cleanup-env` might work?  That is how it currently cleans the environment after a test run.

**Comment by leochr** [comment]
@dtadcox Thanks for looking into this. The steps to uninstall the Operator (documented [here](https://www.ibm.com/docs/en/was-liberty/base?topic=operator-uninstalling)) should be performed first. Then delete the test namespace (above function _cleanup_env_).

**Comment by dtadcox** [comment]
PR1: https://github.com/WASdev/websphere-liberty-operator/pull/412

**Comment by leochr** [comment]
@dtadcox I believe project/namespace delete takes some time. So the actual delete operation (issued at the end of 'OwnNamespace') only seems to complete during 'SingleNamespace'. So I think a check to make sure that the project was indeed deleted is needed. Add a for-loop to check periodically that it's deleted. In case, it gets stuck, exit the for loop after some time (5 minutes) and fail the test. Thank you

**Comment by dtadcox** [comment]
PR2: https://github.com/WASdev/websphere-liberty-operator/pull/426

**Comment by dtadcox** [comment]
All work is complete, closing this issue.
