### ISSUE TITLE
Create multi-arch images for operator, bundle and catalog

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#384]
Current images are single-arch (amd64) only. Enhance the build scripts to produce multi-arch (amd64, p and z) images. Ensure that the manifest is produced correctly and lists images for all archs. Use WebSphere Automation Operator as a reference.

**Comment by halim-lee** [comment]
WLO: https://github.com/WASdev/websphere-liberty-operator/pull/399
RCO: https://github.com/application-stacks/runtime-component-operator/pull/485
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/388

**Comment by leochr** [comment]
Delivered. Closing
