### ISSUE TITLE
Update Operator metadata to declare support for P & Z

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#385]
Update Operator CSV, affinity to declare support for P & Z. Use WebSphere Automation Operator as a reference.

- [x] Delivered to WLO
- [x] Delivered to RCO
- [x] Delivered to OLO

**Comment by halim-lee** [comment]
RCO: https://github.com/application-stacks/runtime-component-operator/pull/485
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/393
