### ISSUE TITLE
Backup operators and containers

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#386]
Start with manually backing up the source code for the operators (WLO, OLO, RCO) and runtime containers (OL, WL, tWAS) and then automate the process (triggered by OnePipeline build).

The process (including git commands) is documented [here](https://github.ibm.com/websphere/WS-CD-Open/wiki/GM-Driver-Process#step-9-push-the-gm-code-to-httpsgithubibmcomwebsphere-compliance).

The following repos have been created in GHE

Operators:
|  Source Of Backup     |   Backup Destination  | Initial Archive Command | Archive Script PR | Pipeline Task Created |
| ----------- | ----------- | ------------- | --------------  | ---------------- |
|[websphere-liberty-operator](https://github.com/WASdev/websphere-liberty-operator)|[websphere-liberty-operator-archive](https://github.ibm.com/websphere-compliance/websphere-liberty-operator-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/websphere-liberty-operator-archive "+refs/remotes/origin/release:refs/heads/release" "+refs/remotes/origin/main:refs/heads/main" "+refs/tags/*:refs/tags/*"` |[PR](https://github.com/WASdev/websphere-liberty-operator/pull/392) | ✓ |
|[open-liberty-operator](https://github.com/OpenLiberty/open-liberty-operator)|[open-liberty-operator-archive](https://github.ibm.com/websphere-compliance/open-liberty-operator-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/open-liberty-operator-archive "+refs/remotes/origin/main:refs/heads/main" "+refs/tags/*:refs/tags/*" `|[PR](https://github.com/OpenLiberty/open-liberty-operator/pull/368)|  ✓ |
|[runtime-component-operator](https://github.com/application-stacks/runtime-component-operator)|[runtime-component-operator-archive](https://github.ibm.com/websphere-compliance/runtime-component-operator-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/runtime-component-operator-archive "+refs/remotes/origin/main:refs/heads/main" "+refs/tags/*:refs/tags/*"`|[PR](https://github.com/application-stacks/runtime-component-operator/pull/454)|  ✓ |

Container Images:
|  Source Of Backup     |   Backup Destination  | Initial Archive Command |Archive Script PR | Pipeline Task Created |
| ----------- | ----------- | -------------- |--------------  | ----------------- |
|[WL Containers](https://github.com/WASdev/ci.docker)|[websphere-liberty-container-images-archive](https://github.ibm.com/websphere-compliance/websphere-liberty-container-images-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/websphere-liberty-container-images-archive "+refs/remotes/origin/main:refs/heads/main"` | [PR](https://github.ibm.com/was-docker/build-liberty-images-ubi/pull/216)| ✓ |
|[OL Containers](https://github.com/OpenLiberty/ci.docker)|[open-liberty-container-image-archive](https://github.ibm.com/websphere-compliance/open-liberty-container-image-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/open-liberty-container-image-archive "+refs/remotes/origin/main:refs/heads/main"` | [PR](https://github.ibm.com/was-docker/build-liberty-images-ubi/pull/216)| ✓ |
|[tWAS Containers](https://github.com/WASdev/ci.docker.websphere-traditional)|[websphere-traditional-container-images-archive](https://github.ibm.com/websphere-compliance/websphere-traditional-container-images-archive)| `git push --prune https://<git_token>@github.ibm.com/websphere-compliance/websphere-traditional-container-images-archive "+refs/remotes/origin/main:refs/heads/main"` | [PR](https://github.ibm.com/was-docker/build-twas-images/pull/120)| ✓ |

* Both Liberty containers keep pipeline scripts here: https://github.ibm.com/was-docker/build-liberty-images-ubi
* tWAS container keeps pipeline scripts here: https://github.ibm.com/was-docker/build-twas-images

**Comment by dtadcox** [comment]
@leochr Do you have a backup location in mind?

**Comment by leochr** [comment]
@dtadcox yes, we'll use the websphere-compliance org in GHE. I just added the locations in the above description.

**Comment by dtadcox** [comment]
@leochr The only source repository that contains a **release** branch is the websphere-liberty-operator.  The remaining 5 projects do not have such a branch.  That is problem now for the initial archives and it will be problem moving forward if we try and automate things.  We need one branch for each (preferably with the same name) that is the release branch.

**Comment by dtadcox** [comment]
@leochr Per our discussion, I have updated the table above to reflect the initial command used to seed the archives.  Please confirm these entries and I will proceed with the actual step of archiving.  I have confirmed both 1) that these commands will work using a test destination and 2) that updating the existing WLO archive will be fine using the new command.

**Comment by dtadcox** [comment]
I've completed the initial archive process.

**Comment by dtadcox** [comment]
Each project will get a new `.one-pipeline-archive.yaml` file.  This new build script is quite simple and will only perform the archive action in the code-setup stanza.  Everything else has been stripped out of the script to enhance run time.  Outside of this script, the rest of the archive tooling is simply part of one-pipeline.  A new `archive` trigger will need to be created for each project.  That trigger should be scheduled to run weekly.  The following are the properties to be set (websphere-liberty-operator is being used as the example):

| Property Name | Property Value |
| --------------- | --------------- |
| app-name         | onepipeline-sample-app |
| archive-destination-repo | github.ibm.com/websphere-compliance/websphere-liberty-operator-archive |
| branch | main |
| pipeline-config | .one-pipeline-archive.yaml |
| pipeline-config-branch | main |
| repository | https://github.com/WASdev/websphere-liberty-operator.git |
| slack_users | @dtadcox @leojc |

**Comment by leochr** [comment]
@dtadcox We only discussed backing up the main and release branches. But it'll be good to back up all branches. This will allow us to retrieve dev branches and avoid setbacks. I hope the current approach for tags (with wildcards) would also work for branches. Thanks.

**Comment by dtadcox** [comment]
@leochr See my previous comment.  The **archive-destination-repo** property will allow any set of branches and/or tags to be designated in the trigger of the build.  This parameter is what is passed into the archive command as the basis of what is archived.

**Comment by dtadcox** [comment]
All new pipeline scripts have been created and all new timed pipeline tasks created.  I am closing the task now.
