### ISSUE TITLE
Kustomize CRD for installing WLO 1.1.0 is not up to date

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#397]
Installed WLO 1.1.0 on EKS cluster using [kustomize](https://www.ibm.com/docs/en/was-liberty/base?topic=cli-installing-kustomize).  I used kustomize files from https://github.com/WASdev/websphere-liberty-operator/tree/main/deploy/releases/1.1.0/kustomize to install WLO 1.1.0, but when deploy app with semeruCloudCompiler enable, it  throws the following error:
```
error: error validating "deploy-microwebapp-eks.yaml": error validating data: ValidationError(WebSphereLibertyApplication.spec): unknown field "semeruCloudCompiler" in com.ibm.websphere.liberty.v1.WebSphereLibertyApplication.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
 Looking at the websphere-liberty-controller-manager  deployment, it's using

> image: [icr.io/cpopen/websphere-liberty-operator@sha256:1fd1aafb184f722a1073d11a2ab0a38056c1709bc6805548ba50161562435f8a](http://icr.io/cpopen/websphere-liberty-operator@sha256:1fd1aafb184f722a1073d11a2ab0a38056c1709bc6805548ba50161562435f8a)

Look like kustomize CRD is not up-to-date

**Comment by leochr** [comment]
The type definition for `.spec.semeruCloudCompiler` was missing from CRD for 1.1.0 release, which caused the above issue. CRD was updated to include it. Closing.
