### ISSUE TITLE
Modify CSV description as per linter requirements

### ISSUE THREAD

**Issue by idlewis** [WASdev/websphere-liberty-operator#41]
The description in the CSV must match the linter rules:
" the CSV description must contain the same sections as the case README in markdown."

```spec:
  description: |-
    # Introduction
    # Details
    Various Details
    ## Prerequisites
    Various prerequisites
    ## Resources Required
    Various Resources Required
    ## Installing
    Various Installation details
    # Configuration
    Various Configuration information
    ### Limitations
    Various Limitations
    ### SecurityContextConstraints Requirements
    SCC Requirements
```

**Comment by leochr** [comment]
@idlewis thanks for opening this issue. Please do the same for other linter items that are not small. This particular requirement comes from Certification and I have this issue already opened: https://github.com/WASdev/websphere-liberty-operator/issues/30
