### ISSUE TITLE
Setup NFS storage for OCP

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#418]
Setup NFS storage (server and provisioner) and update [configure-cluster.sh](https://github.ibm.com/websphere/operators/blob/main/scripts/configure-cluster/configure-cluster.sh)

**Comment by halim-lee** [comment]
RCO: https://github.com/application-stacks/runtime-component-operator/pull/492
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/388
WLO: https://github.com/WASdev/websphere-liberty-operator/pull/431
