### ISSUE TITLE
Support building multi-arch images but test only on X by default

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#433]
At the moment, the flag to build multi-arch images is also used to control which platforms to run the tests on. 

The current flag is `architecture` - can be `X` or `ZXP`).

We need a way to build multi-arc images, but be able to test only on X. It should be the default configuration in pipeline.

Couple of options:
- provide `build-architecture` and `test-architecture` flags;
OR
- continue to use the `architecture` flag, but provide a new flag (i.e. SKIP_OCP_TESTS_ON_P) - which defaults to true

- [ ] Delivered to WLO
- [ ] Delivered to RCO
- [ ] Delivered to OLO

**Comment by halim-lee** [comment]
Will be delivered with: https://github.com/WASdev/websphere-liberty-operator/issues/470
