### ISSUE TITLE
Resolve affinity and ingress test failures in kind-cluster 

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#438]
```
Results:
	Name: affinity
	State: fail
...
...

	Errors:
		resource StatefulSet:wlo-test/affinity-other-rc: .status.readyReplicas: key is missing from map

	Name: ingress-certificate
	State: fail

	Errors:
		resource Deployment:wlo-test/ingress-with-cert-rc: .status.readyReplicas: key is missing from map

	Name: ingress
	State: fail

	Errors:
		resource Deployment:wlo-test/ingress: .status.readyReplicas: key is missing from map

...
...
	
****** Test results
[FAILED] kind-e2e-run: Exited (2) 47 seconds ago
[PASSED] ocp-e2e-run-X
```	

Failures are seen in these builds:
[WLO 1082](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/d2f53b41-5163-48a2-bfe7-7c1966138da3/code-ci-finish/finish?env_id=ibm:yp:us-south) - April 13, 2023
[WLO 1079](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/5b3060b4-5365-4893-890c-df8892ac55c9/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south) - April 10, 2023
[WLO 1075](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/942e1e69-a317-41c8-bc16-9a97b0d07288/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south) - April 6, 2023

**Comment by halim-lee** [comment]
Seems to be related to pause image. [scripts/e2e-kind.sh](https://github.com/WASdev/websphere-liberty-operator/blob/main/scripts/e2e-kind.sh#L10) is still trying to find pause:2.0 to add runAsRoot. Will be addressed as part of https://github.com/WASdev/websphere-liberty-operator/pull/445

**Comment by leochr** [comment]
Thank you Melissa!

**Comment by halim-lee** [comment]
Delivered through https://github.com/WASdev/websphere-liberty-operator/pull/445
