### ISSUE TITLE
Add e2e tests for annotations on service certificates

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#440]
Add e2e tests for annotations on service certificates

Issue: https://github.com/wasdev/websphere-liberty-operator/issues/424
PR: https://github.com/application-stacks/runtime-component-operator/pull/484

- [x] Completed for WLO
- [x] Completed for RCO
- [x] Completed for OLO

**Comment by kabicin** [comment]
I created https://github.com/WASdev/websphere-liberty-operator/issues/515 to track the documentation update as well.

**Comment by kabicin** [comment]
Closing since it is completed with https://github.ibm.com/websphere/operators/pull/37
