### ISSUE TITLE
Add tests for handling k8s resource conflict due to same CR names

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#442]
Add tests for the scenario addressed by https://github.com/WASdev/websphere-liberty-operator/issues/179

- [ ] Delivered to RCO
- [ ] Delivered to OLO
- [ ] Delivered to WLO

**Comment by kabicin** [comment]
kind-kuttl tests were merged into common repo with https://github.ibm.com/websphere/operators/pull/50 which covers tests for all operators

**Comment by leochr** [comment]
Closing as completed
