### ISSUE TITLE
Investigate the Linter ERROR RequiredMetadataLabelsDefined

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#448]
Investigate the Linter ERROR RequiredMetadataLabelsDefined: https://certification.cloudpaklab.ibm.com/#/certifications/certView/0fb8f024-ad80-4f06-9f2a-aa4971843b55/lint/preReleaseResults

Reference: 
https://playbook.cloudpaklab.ibm.com/code-standards-linting/code-standards-libary/standards-index/RequiredMetadataLabelsDefined

ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-configmap-waobgaz-dyn-0-websphere-liberty-operator.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels
-- | -- | -- | -- | -- | -- | -- | --
ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-operatorgroup-waobgaz-dyn-0-ibm-websphere-liberty-catalog-group.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels
ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-secret-waobgaz-dyn-0-websphereliberty-app-sample-svc-tls-ocp.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels
ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-webspherelibertyapplication-waobgaz-dyn-0-websphereliberty-app-sample.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels
ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-webspherelibertydump-waobgaz-dyn-0-websphereliberty-dump-sample.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels
ibmcase-bundle-test/test-op-olm | ERROR | RequiredMetadataLabelsDefined |   | scanned-webspherelibertytrace-waobgaz-dyn-0-websphereliberty-trace-sample.yaml | ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels | ERROR | Pod IdentificationKubernetes Common Labels

**Comment by idlewis** [comment]
The first error is due to missing labels in the operator config map.
That will require fix to utils from RCO.
Others are all false positives. The linter is scanning installed sample CRs, rather that operator owned resources. As there is no way to add labels to the secret 'websphereliberty-app-sample-svc-tls-ocp' (this is generated by OCP), these will need to be ignored.
