### ISSUE TITLE
Operator shows incorrect version after airgap install

### ISSUE THREAD

**Issue by bconey** [WASdev/websphere-liberty-operator#450]
After completing an airgap install for pre-GA 1.2.0 version, viewing the operator in the OCP console indicates that it is at 1.1.0.

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/31766760/233093037-3180d749-92e7-4f65-85c2-5d5c0e76c74c.png">

**Comment by leochr** [comment]
The operator version is 1.2.0. The Subscription in CASE should specify v1.2 instead of v1.1 ([here](https://github.ibm.com/websphere/liberty-case-bundle/blob/192776017053dd5fad7cf15d05e16256e6f2398a/submodules/shared_scripts/launch-impl.sh#L12))

**Comment by mcurran-us** [comment]
The CASE has been update to use channel v1.2 ([here](https://github.ibm.com/websphere/liberty-case-bundle/blob/65a957cd3ce1d6d61e1ccf35b0a45228a87385aa/submodules/shared_scripts/launch-impl.sh#L12) and the CASE has been updated [here](https://github.ibm.com/IBMPrivateCloud/cloud-pak/blob/master/repo/case/ibm-websphere-liberty/1.2.0/ibm-websphere-liberty-1.2.0.tgz)

**Comment by bconey** [comment]
Verified fix.
