### ISSUE TITLE
Share the pipeline scripts and artifacts between the operators

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#470]
- Evaluate the differences between the pipeline yaml and scripts of RCO, OLO and WLO
- Move the pipeline stages to individual scripts
- Share the scripts between the operators (use https://github.ibm.com/websphere/operators)

**Comment by halim-lee** [comment]
- [x] Delivered to WLO
- [ ] Delivered to RCO
- [ ] Delivered to OLO
