### ISSUE TITLE
Run the e2e tests with OCP 4.13 GA 

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#476]
OCP 4.13 is expected to be available in May 2023. Run the e2e tests on all architectures using OnePipeline. Address (or open separate workitems) for any failures related to OCP/Kubernetes versions

**Comment by halim-lee** [comment]
- Kuttl tests against OCP 4.13 all passed. Will test against kind cluster on Kubernetes v1.26

**Comment by halim-lee** [comment]
OCP tests pass: https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/6421743a-97cb-432f-be83-ed2364facb87/code-ci-finish/run-stage?env_id=ibm:yp:us-south
