### ISSUE TITLE
Update to deal with prometheus scheme validation

### ISSUE THREAD

**Issue by idlewis** [WASdev/websphere-liberty-operator#492]
This commit in prometheus:
prometheus-operator/prometheus-operator@28e0383
has added scheme validation, and only allows http or https as valid values.
We currently set 'HTTPS' which will not be allow

Needs fixing in:

- [x] rco
- [x] olo
- [x] wlo

**Comment by idlewis** [comment]
Fixed in RCO via application-stacks/runtime-component-operator#545

**Comment by idlewis** [comment]
WLO tests fixed vi WASdev/websphere-liberty-operator#497

**Comment by leochr** [comment]
Closing as completed
