### ISSUE TITLE
Use zone topology within the default affinity

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#499]
Default affinity uses `topologyKey: kubernetes.io/hostname`. Consider using `topologyKey: topology.kubernetes.io/zone` instead to spread the pods across zones

**Comment by kabicin** [comment]
Closing since the changes are merged into RCO and pulled into WLO with https://github.com/WASdev/websphere-liberty-operator/pull/514 and into OLO with https://github.com/OpenLiberty/open-liberty-operator/pull/497
