### ISSUE TITLE
Include the sample app as part of the periodic rescan of latest release

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#502]
As part of the periodic rescan of the latest release of our Operators, we should include the Liberty's Getting Started Sample app. It is referenced from our sample CR using a digest value. The image with digest value should be included in the scans to identify any CVEs flagged against it.

The periodic rescan skips building the images in the _build-containerize_ stage and adds the release images (for operator, bundle and catalog) which are later loaded and scanned. Hence, one approach could be to look up the sample app image value referenced in the release and add it.

**Comment by dtadcox** [comment]
PR: https://github.com/WASdev/websphere-liberty-operator/pull/516
