### ISSUE TITLE
[scan] Assess the whitesource scan results

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#51]
OnePipeline doesn't support whitesource at this time. It's on their roadmap. Alternative is to use GitHub Enterprise, which provides whitesource, to scan the operator source (the source has to be copied to GH Enterprise repo - not sure if there is a way to link to this GH public repo).

Following the guidelines from https://pages.github.ibm.com/Whitesource-IBM/whitesource/, the whitesource scan is enabled on the GitHub enterprise repo: https://github.ibm.com/websphere/liberty-operator

It links to this repo as a submodule. But it hasn't triggered a scan. Find a way to scan it and then assess the results. Whitesource should raise GitHub issues for the CVEs it detects. For WLO, expect at least a few issues to be reported.

Slack channel for requesting help with whitesource: #sos-whitesource

**Comment by leochr** [comment]
@smcclem Looked at the last commit in GHE repo, and it did trigger a whitesource scan ([here](https://github.ibm.com/websphere/liberty-operator/runs/6685810)). But it didn't scan the WLO submodule (the total libraries scanned says 0). Heard that Dave Cohen from OnePipeline squad is also looking into enabling the whitesource scan for other repos. Please check with him to see if he has any suggestions on how to scan with the submodule approach. Last resort would be to check in the source code from this public GH repo into GHE repo.

**Comment by leochr** [comment]
OnePipeline clones the branch to GHE repo automatically whenever a build is kicked off. Issues are opened by whitesource on the GHE repo: https://github.ibm.com/websphere-compliance/websphere-liberty-operator-whitesource-scan/issues

The 4 open issues are for the CVEs that we already analyzed and concluded as 'waiting for fix from vendor', fyi @mingcyu

**Comment by leochr** [comment]
There is a new CVE from WhiteSource scan: https://github.ibm.com/websphere-compliance/websphere-liberty-operator-whitesource-scan/issues/5

@smcclem could you please investigate? Thanks

**Comment by mingcyu** [comment]
Scott updated directly in the whitesource scan. I've also updated the spreadsheet to include the new CVE
