### ISSUE TITLE
[linter] Analyze and resolve the new static linter results

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#53]
Static linter results as of 4/6. Level of operator code, commit https://github.com/WASdev/websphere-liberty-operator/commit/90e47647c75299d0721fe8cba4ab6170e1a3df33
[static-lint.txt](https://github.com/WASdev/websphere-liberty-operator/files/8430428/static-lint.txt)

The static linter now runs as part of OnePipeline.

**Comment by leochr** [comment]
Some of these should have been addressed in the latest driver: CSVDefinesCRDWithValidDescription, CRDDefinesLicenseProperty

Scan with linter again. OnePipeline doesn't get to the step to scan with linter due to e2e tests step failing (cluster issue).

**Comment by idlewis** [comment]
Running the linter v3.1.1 locally against the case bundle and the main branch of the WLO, I'm getting no 'ERROR' output, only review/warnings

**Comment by mcurran-us** [comment]
[static-lint-results-4-12-22.txt](https://github.com/WASdev/websphere-liberty-operator/files/8476727/static-lint-results-4-12-22.txt)

**Comment by mcurran-us** [comment]
Static linter results for websphere-liberty-operator commit [https://github.com/WASdev/websphere-liberty-operator/commit/30b9d6495f73afb76e9fa48c07cb7ca33858ddd0
[static-lint-results-4-19-22.txt](https://github.com/WASdev/websphere-liberty-operator/files/8514746/static-lint-results-4-19-22.txt)
]

**Comment by leochr** [comment]
Reviewed the latest results. There are no errors. The warnings are false positives.
