### ISSUE TITLE
Generate LTPA key 

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#530]
Generate and store the LTPA key in a Kubernetes secret

Evaluate the following options to generate the LTPA key:
- Using go (assuming there are suitable libraries already)
- Using securityUtility command-line option from Liberty
- Stand-alone Java service

**Comment by leochr** [comment]
@kabicin Please try the approach to invoke the Kubernetes API using curl/HTTPS-request (see references below) to create the Secret. So the same container (in Job's Pod) that invokes `securityUtility` would also create the Secret with an encoded password and the generated LTPA token. You'll have to configure RBAC to allow the Pod's service account to provide permission to create/get Secret. 

It's probably ideal to have a script that's invoked to perform all of these. The alternative is to execute the commands directly using .spec.containers[].command.

https://v1-25.docs.kubernetes.io/docs/tasks/run-application/access-api-from-pod/
https://prathapreddy-mudium.medium.com/accessing-the-kubernetes-api-from-a-pod-b38c5c775ce8
https://stackoverflow.com/questions/30690186/how-do-i-access-the-kubernetes-api-from-within-a-pod-container

**Comment by kabicin** [comment]
Closing since it's merged with updates https://github.com/WASdev/websphere-liberty-operator/pull/533, https://github.com/WASdev/websphere-liberty-operator/pull/564, https://github.com/WASdev/websphere-liberty-operator/pull/565, and https://github.com/WASdev/websphere-liberty-operator/pull/575
