### ISSUE TITLE
Mount the generated LTPA key

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#531]
Use volume mount to propagate the LTPA key to all application instances (replicas)

**Comment by leochr** [comment]
@kabicin For any non-dynamic LTPA changes which require application/server restart, it's best to set the resource version of secret/configmap (that includes the new value) as an environment variable. This will roll out the new pods while keeping some of the old pods based on the update strategy user sets. We do this for Service account ([here](https://github.com/application-stacks/runtime-component-operator/blob/7bc7bccc151c95f35dd9a572e00710d34076ef3b/utils/utils.go#L691)). There is also a helper method that can do this for secret ([here](https://github.com/application-stacks/runtime-component-operator/blob/7bc7bccc151c95f35dd9a572e00710d34076ef3b/utils/utils.go#L1518)). 
https://github.com/application-stacks/runtime-component-operator/blob/7bc7bccc151c95f35dd9a572e00710d34076ef3b/utils/utils.go#L1518

This would be a better approach than directly dealing with Pods and/or deleting Deployment/StatefulSet (which will affect application availability).

**Comment by kabicin** [comment]
Closing since it's merged with updates https://github.com/WASdev/websphere-liberty-operator/pull/533, https://github.com/WASdev/websphere-liberty-operator/pull/564, https://github.com/WASdev/websphere-liberty-operator/pull/565, and https://github.com/WASdev/websphere-liberty-operator/pull/575
