### ISSUE TITLE
Add observedGeneration field to WLA status

### ISSUE THREAD

**Issue by arturdzm** [WASdev/websphere-liberty-operator#560]
To improve ability to check if spec matches reconciled version 
spec.generation should be copied into status.observedGeneration once all resources are updated / created.

**Comment by leochr** [comment]
Opened issue in OLO repo (so it can be tracked as part of Liberty runtime and Operator requirements for App Flow): https://github.com/OpenLiberty/open-liberty-operator/issues/535
