### ISSUE TITLE
WLO Application is not deploying with `manageLTPA: true`

### ISSUE THREAD

**Issue by mtamboli** [WASdev/websphere-liberty-operator#571]
I deployed the latest 1.3 WLO on OCP 4.12 cluster. I installed the sample application and made 2 changes to the config and kept everything default. 
```
manageLTPA: true
replicas: 3
```

<img width="1079" alt="image" src="https://github.com/WASdev/websphere-liberty-operator/assets/29490950/0e069c94-a8c2-4218-a2e9-f5d84232bd70">

<img width="929" alt="image" src="https://github.com/WASdev/websphere-liberty-operator/assets/29490950/de2fbd6d-17cd-4ed8-850b-fe19f7d3c318">

**Comment by leochr** [comment]
[WLO wiki](https://github.com/WASdev/websphere-liberty-operator/wiki) is updated with a new driver details that addresses the reported [packaging issue #571](https://github.com/WASdev/websphere-liberty-operator/issues/571).

An LTPA script was not packaged with the Operator. This issue doesn’t occur when testing Operator locally. We are working on FVT tests for LTPA scenarios, which would catch such issues.

**Comment by mtamboli** [comment]
Thank you @leochr ! So we should not test LTPA key scenario with this new operator?

**Comment by leochr** [comment]
@mtamboli LTPA scenarios can be tested with the new driver. I was just trying to explain the cause of the issue. It's fixed in the new driver.

**Comment by mtamboli** [comment]
I am able to verify that issue is resolved and application pods are started up fine and see that managed LTPS keys are being used.
```
more /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/managedLTPA.xml
<?xml version="1.0" encoding="UTF-8"?>
<server>
    <ltpa keysFileName="${server.config.dir}/managedLTPA/ltpa.keys" keysPassword="{aes}AOVFQIDGUK3g6y77eT/wN6aytc6xwDeq+xJvDQhJ5Vm+4HVHaQDysFY
Y5fad97R/ig==" />
</server>
sh-4.4$ cd 
sh-4.4$ cd config/
sh-4.4$ ls
apps  configDropins  dropins  managedLTPA  server.xml
sh-4.4$ cd managedLTPA/
sh-4.4$ ls
ltpa.keys
sh-4.4$ more ltpa.keys 
#Wed Nov 01 18:20:02 UTC 2023
com.ibm.websphere.ltpa.version=1.0
com.ibm.websphere.ltpa.3DESKey=JK9mDplX33/L9J0iko6I5VLcyfSsZJ56NDhBLAmCwQ0\=
com.ibm.websphere.ltpa.PrivateKey=Ugruu0l3sr3SqEbQvFqVTQivBF2fyMyHB/6rtjx8Unrdxje026fqXJyas37LaQaXw0z+itJbi2pX7fSZbJXyAC2KgpEahBK3059Ssf2qelDf
AjpkIbaqplt5EcU7SGQyotid5tvU0DSQupsvrxFyw12d0l9HnE2PWVfJhwkX0/qF0BJ8veDRULVjGD3ILvMDcF3BRcfI9WLNps5SenvT6C6wrzYFlINW9RqnbXrsOxEbwBGJzGf95NncSe
vZYR/ZAVnQ9EbW2LzCVmHWGXznmPmeZ5MfQoKA1zhDMlz1YlEfFaoUwT7fMK9f2juT40RdlvDoOzWKxHKsJB7/XwgZjhnl0v0LEG1JDYxpqE5Ifmk\=
com.ibm.websphere.CreationHost=localhost
com.ibm.websphere.ltpa.Realm=defaultRealm
com.ibm.websphere.ltpa.PublicKey=AJQ0RQPB9FM+v9iJw/jcAcP8yRBOpp6kop5hVprwy3dLv31HqAmVR90/Sbk1tne0d8m9I9URvis72b6cufdqFmeFmIV0dhwFwcHEblZjyevYq
FslDbSgKeYUnlM3hpqyn4qXZKXwIU19wssXaRIph+wxjnAcj11ULUdmZ5n82WZvAQAB
com.ibm.websphere.CreationDate=Wed Nov 01 18\:20\:02 UTC 2023
```
