### ISSUE TITLE
Allow custom metering/license annotations

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#597]
WLO sets the metering/license annotations on application pods based on the values specified for `.spec.license.*` fields in WebSphereLibertyApplication CR. The values for the fields are a set of pre-defined enum values, which allow users to select their license entitlement easily. 

License annotations added via deployment/statefulset annotations and/or CR metadata are replaced with the values specified for `.spec.license.*`. But in some cases, stack products would require custom license annotations to be set on the pods. Provide an option to skip the standard metering annotations so that custom metering annotations can be added (using one of the mechanisms mentioned above).

Since this is only meant for stack products, I suggest supporting this configuration via an annotation on WebSphereLibertyApplication CR's metadata as opposed to a new config field (in spec)
Suggestion: `liberty.websphere.ibm.com/exclude-licensing-annotations`

**Comment by idlewis** [comment]
@leochr 
When skipping these annotations, there are the license annotations:
```
pts.Annotations["productID"]
pts.Annotations["productChargedContainers"]
pts.Annotations["productMetric"]
pts.Annotations["productName"]
```
And also the three cloud pak related annotations:
```
pts.Annotations["cloudpakName"]
pts.Annotations["productCloudpakRatio"]
pts.Annotations["cloudpakId"]
```
Should we be skipping both sets of annotations?

**Comment by leochr** [comment]
@idlewis Yes, both sets of annotations should be skipped (License Services considers both sets)

**Comment by leochr** [comment]
We've reverted this based on the recent discussions. There wasn't any confirmation from the Paris team that this is still needed.

The suggestion is to use Open Liberty Operator when the functionality to automatically add Liberty license annotations is not needed. WLO will always add Liberty license annotations based on the default/selected entitlement source and there will not be any way to disable/override the added license annotations
