### ISSUE TITLE
Clean up the logs from the LTPA Job's pod

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#629]
LTPA Job's pod includes some information that should be excluded/cleaned up. 

These are output to log by curl and securityContext commands, not by explicit echo/cat statements

**Comment by kabicin** [comment]
PRs ready for review
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/572
WLO: https://github.com/WASdev/websphere-liberty-operator/pull/636
