### ISSUE TITLE
Update the licenses in the CASE

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#644]
Update the licenses in the CASE package

**Comment by leochr** [comment]
@kabicin Please update the licenses in the CASE with the ones from https://www.ibm.com/docs/en/was-liberty/base?topic=installation-viewing-license-information

We can use the links in the above documentation in case.yaml. We don't need to create short urls.

**Comment by leochr** [comment]
@kabicin The license files are in this box folder: https://ibm.ent.box.com/folder/263704413464

Within the zip file you'll find many licenses. Please use the UTF-8 version of the license file (<ZIP_FILE>/UTF8/LA_en).


Please add the following statement (as in [this existing file](https://github.ibm.com/websphere/liberty-case-bundle/blob/fd92b49804c6a891421497b71c88eef24b0343d9/stable/ibm-websphere-liberty-bundle/case/ibm-websphere-liberty/licenses/L-AMIK-BYM26G_LA_en#L1)) at the top of each License file. Use the link in the [license doc](https://www.ibm.com/docs/en/was-liberty/base?topic=installation-viewing-license-information) for each license instead. Exclude `&lc=en` at the end of the link. 

```
The translated license terms can be viewed here: <link>

```

For example, for `IBM Cloud Pak for Applications 5.2`:

```
The translated license terms can be viewed here: https://www.ibm.com/support/customer/csol/terms/?id=L-YQXD-3APM2Q

```

Thank you

**Comment by kabicin** [comment]
Thanks for the review/merge, I updated the pre-release CASE tgz on the cloud-pak repo to reflect the changes.
