### ISSUE TITLE
BYOE tool needs either a docker or podman install in the test container

### ISSUE THREAD

**Issue by yongja79** [WASdev/websphere-liberty-operator#653]
The BYOE tool currently fails with the following error

```[ERROR] inventory/websphereLibertyOperatorSetup/resources.yaml: Catalog icr.io/cpopen/websphere-liberty-operator-catalog@sha256:3413030587e4312228d9a089c7b1f8900989838945df8cfd9ca5799b0bd8352a is missing or unable to be extracted (CatalogImageMissing)```

It is trying to pull the catalog image using podman but the UBI image doesn't have that installed. As that test container is running in a container there are a couple of options

1. Podman in Docker (PinD). Podman needs to be setup in the test container. Podman installed in the test container which then needs to talk to the Docker demon running in the acceptance test stage container. Documentation suggests its possible but no instructions on how to do it https://www.redhat.com/sysadmin/podman-inside-container
2. Podman in Podman (PinP). Podman installed in both acceptance test stage and test containers. This may not work as technically the acceptance test stage container itself is running Docker in Docker (DinD)
3. Docker in Docker (DinD). Find a way to install docker in a UBI image. Currently the UBI images do not have a valid install for Docker as only s390 is supported on a RHEL image. However the documentation does suggest trying the CentOS image (https://docs.docker.com/engine/install/rhel/). This may be the best way forward. If this is done the call to the BYOE needs to be modified and `--container-tool docker` added

**Comment by yongja79** [comment]
Fixed as par of https://github.ibm.com/websphere/operators/pull/136

**Comment by leochr** [comment]
PR https://github.ibm.com/websphere/operators/pull/136 was merged. Closing.
