### ISSUE TITLE
WLO (and OLO) 1.4 uninstall/Re-install not working as expected

### ISSUE THREAD

**Issue by mtamboli** [WASdev/websphere-liberty-operator#680]
I installed preious version of the operator or RC2 and uninstalled it cleanly. Then I updated the catalog with the new operator RC3 image. I tried to re-install WLO/RCO and got into this error.

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/8464d469-4634-4421-9717-909df7a35091">

I removed the websphere-loiberty-opgroup and then got into next problem
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/3207cc3b-7edf-42a4-84ac-492836122f8d">

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/b4cae0cd-022c-44b2-8bed-de3b4456331e">

**Comment by leochr** [comment]
Based on the Slack discussion with @mtamboli. The GA version of WLO (1.3.3) was installed by GitOps alongside 1.4.0. That explains the above conflicts with Operator groups and subscriptions. There can only be one instance for those. Closing as cluster issue.

**Comment by mtamboli** [comment]
I think this is the scenario:

1. Installed 1.4 RC driver
2. GitOPs deployment of application installed 1.3.x driver
3. I uninstalled 1.3.x and pretty sure it reverted back to 1.4.
4. In this case CRD is still 1.3.x?
