### ISSUE TITLE
Validate Airgap for WLO 1.4.1

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#707]
Validate Airgap for WLO 1.4.1 using the automated scripts/artifacts (with some manual steps as needed)

**Comment by idlewis** [comment]
Manual testing complete against
image: icr.io/cpopen/websphere-liberty-operator@sha256:896a4dcaeb4cc02e4b5f29fc090e1de77309ca7447761ecf31ce92b2eb18b2bb
No issues found

**Comment by leochr** [comment]
@idlewis Thank you.

Closing as completed.
