### ISSUE TITLE
[1P] An option to skip scans in OnePipeline

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#75]
Running the entire pipeline takes time. Add an option to skip scans, so a dev driver can be obtained with unit and e2e test verification.

**Comment by dtadcox** [comment]
I did some investigation on the time consumed by each stanza of the one-pipeline build.  So, looking over some of the recent builds, there are three stanzas that consume an equally large portion of the time it takes to complete a build.  They are code-ci-compliance, build-containerize and deploy-acceptance-tests.  These three stanzas (when all are completing successfully) are taking roughly 90% of the total time.  There are three different stanzas that do some type of scanning from what I can tell.  Those three are code-static-scan, code-ci-compliance and build-scan-artifact.  Of these three, only code-ci-compliance takes any noticeable amount of time.  Static scan usually completes in under a minute and scan-artfact in just over a minute to two minutes.  The code-ci-compliance on the other hand consistently is running close to 15 minutes or more.  That stanza handles the detect secrets and run-cra.  The bulk of the time is in run-cra.  I do not know what run-cra does, but the more important fact is that we do not control the flow through this stanza.  It is not one of the .one-pipeline.yaml sections.  It seems that stanza is controlled inside of one-pipeline core and not extensible to our project. I don't see much value in adding a skip to the other scans.

**Comment by dtadcox** [comment]
Followed up with Paul Baity and confirmed the **code-ci-compliance** step in one-pipeline builds is not configurable.  The outline doc for custom scripting in one-pipeline is here: [https://pages.github.ibm.com/one-pipeline/docs/#/custom-scripts](https://pages.github.ibm.com/one-pipeline/docs/#/custom-scripts).  Notice that the **code-ci-compliance** stage is not included in the table of _User defined custom scripting._
