### ISSUE TITLE
Config Map missing in operators global namespace

### ISSUE THREAD

**Issue by jagraj** [WASdev/websphere-liberty-operator#94]
I installed WebSphere Liberty operator in  global (openshift-operators) namespace. I created sample application CR with all the defaults.
I do see sample application installed with default `manageTLS: true` option. The operator created all the resources needed for the sample to work with default OpenShift certificates. There should be a Config Map created under global namespace to override certificate issuer properties and I can not find this Config Map.

Here is the output from openshift-operators namespace.

```
oc get cm -n openshift-operators
NAME                         DATA   AGE
7111f50b.websphere.ibm.com   0      5h34m
kube-root-ca.crt             1      29h
openshift-service-ca.crt     1      29h

```

**Comment by leochr** [comment]
@jagraj thanks for reporting this. Installing the operator in a single-namespace can be used as a workaround to validate certificates related functionality involving ConfigMap.

**Comment by leochr** [comment]
@mtamboli @tam512 @bconey Is this issue also seen on AKS or EKS cluster when the operator is installed to watch all namespaces (entire cluster)?

**Comment by bconey** [comment]
@leochr  On my EKS cluster I see the following related to the operators namespace created from the install of OLM.  This is  after the WebSphere Liberty operator was installed (watching all namespaces) and the install of an application with manageTLS defaulting to true.  

```
$ kubectl get cm -n operators
NAME                         DATA   AGE
7111f50b.websphere.ibm.com   0      2d17h
kube-root-ca.crt             1      2d17h
```

**Comment by tam512** [comment]
below is from Azure AKS cluster, I installed CatalogSource on _olm_ namespace and subscription on _operators_ namespace.  Installed sample daytrader7 with default manageTLS (_true_) and installed cert manager.

```
$ oc get cm -n operators
NAME                         DATA   AGE
7111f50b.websphere.ibm.com   0      22h
kube-root-ca.crt             1      41h
```

**Comment by leochr** [comment]
Thanks @bconey @tam512 for trying and reporting the behaviour on non-OpenShift environments.

@smcclem fyi, the above results confirm that it's not an OpenShift-specific issue. But an issue specific to AllNamespace install mode. So it's not necessary to try installing on a namespace other than openshift-operators on OpenShift.

**Comment by leochr** [comment]
@tam512 @bconey in which namespace is the instance(s) of WebSphereLibertyApplication created in your scenario? Same namespace as the WLO operator or another namespace? In the another-namesapce scenario, is the `websphere-liberty-operator` ConfigMap present in that namespace?

**Comment by bconey** [comment]
Different namespaces for me (FYI ....  I'd previously done a test for ebuy using OpenLiberty operator which may account for the 2 configmap entries below in that namespace)

```
$ $ oc get wlapps -A -o=custom-columns=NAME:.metadata.name,Namespace:.metadata.namespace
NAME         Namespace
ebuy-dbos    ebuy
daytrader7   sample-daytrader7


$ oc get cm -n sample-daytrader7
NAME               DATA   AGE
kube-root-ca.crt   1      2d18h


$ oc get cm -n ebuy
NAME                           DATA   AGE
7111f50b.apps.openliberty.io   0      39h
kube-root-ca.crt               1      39h
```

**Comment by tam512** [comment]
For AKS env, I installed daytrader on namespace _sample-daytrader7_
```
$ oc get wlapps -A -o=custom-columns=NAME:.metadata.name,Namespace:.metadata.namespace -n sample-daytrader7
NAME         Namespace
daytrader7   sample-daytrader7

$ oc get cm -n sample-daytrader7
NAME               DATA   AGE
kube-root-ca.crt   1      43h
```

**Comment by smcclem** [comment]
@jagraj @tam512 @bconey  This issue should be fixed now, can you please confirm?

**Comment by tam512** [comment]
I installed the latest WLO on Azure AKS cluster, I see config map _websphere-liberty-operator_ in operators namespace but not in the namespace where WebSphereLibertyApplication is installed.  
```
$ oc get cm -n operators
NAME                         DATA   AGE
7111f50b.websphere.ibm.com   0      14d
kube-root-ca.crt             1      14d
websphere-liberty-operator   3      31m


$ oc get wlapps -A -o=custom-columns=NAME:.metadata.name,Namespace:.metadata.namespace -n sample-daytrader7
NAME         Namespace
daytrader7   sample-daytrader7
 
$ oc get cm -n sample-daytrader7
NAME               DATA   AGE
kube-root-ca.crt   1      14d
```

**Comment by leochr** [comment]
@tam512 Thanks for trying the updated driver and confirming that the ConfigMap is in the operator's namespace. It's not expected to be in the WebSphereLibertyApplication namespace. It should only be in operator's namespace, so it's a single resource to specify config.

**Comment by jagraj** [comment]
@leochr @smcclem 
I verified this config map does exist at global operator namespace with the latest build but I did not verify in custom operator namespace. Once we verify in custom namespace then we can close this issue.

`oc get cm -n openshift-operators | grep websphere`

```
7111f50b.websphere.ibm.com       0      26d
websphere-liberty-operator       3      5d19h

```

`oc get cm websphere-liberty-operator -n openshift-operators -o yaml`

```

apiVersion: v1
data:
  certManagerCACertDuration: 8766h
  certManagerCertDuration: 2160h
  defaultHostname: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T18:12:52Z"
  name: websphere-liberty-operator
  namespace: openshift-operators
  resourceVersion: "21453723"
  uid: 449e8235-b930-4798-b21c-bd95653ec28b

```

**Comment by mtamboli** [comment]
**Scenario**: Installed operator on `wlo-install` ns and watching a different ns `wl`.  This install is only using CLI. Followed instructions from the doc:

* set Env variables
```
export WLO_NAMESPACE=wlo-install
export WLO_TARGET_NAMESPACE=wl
 oc create ns wlo-install
 oc create ns wl
```

-  Created wlo catalog (pre-GA)
- Created operator group
```
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-websphere-liberty
  namespace: $WLO_NAMESPACE
spec:
  targetNamespaces:
  - $WLO_TARGET_NAMESPACE
EOF
  ```
- Create a subscription - Had to update the catalog name for pre-GA
```
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-websphere-liberty
  namespace: $WLO_NAMESPACE
spec:
  installPlanApproval: Automatic
  name: ibm-websphere-liberty
  source: wlo-catalog
  sourceNamespace: openshift-marketplace
EOF
```
* Config maps in the namespace where operator is created
```
 oc get cm -n wlo-install
NAME                         DATA   AGE
7111f50b.websphere.ibm.com   0      28m
kube-root-ca.crt             1      35m
openshift-service-ca.crt     1      35m
websphere-liberty-operator   3      21m
```
```
 oc get cm websphere-liberty-operator -n wlo-install -o yaml
apiVersion: v1
data:
  certManagerCACertDuration: 8766h
  certManagerCertDuration: 2160h
  defaultHostname: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-23T14:40:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:certManagerCACertDuration: {}
        f:certManagerCertDuration: {}
        f:defaultHostname: {}
    manager: manager
    operation: Update
    time: "2022-05-23T14:40:42Z"
  name: websphere-liberty-operator
  namespace: wlo-install
  resourceVersion: "2194498"
  uid: 22a35bd7-af6a-48c1-827d-7694e78ab465
```
@jagraj Is this what we wanted to verify?

**Comment by mtamboli** [comment]
This is fixed.
