### ISSUE TITLE
Create page in IBM Docs that lists the licenses for WebSphere with instructions on how to check

### ISSUE THREAD

**Issue by mingcyu** [WASdev/websphere-liberty-operator#95]
As part of the legal review of the way we are implementing our license acceptance, we will link out to a place that provides information on the available licenses as well as instructions on how to check container for that information

**Comment by mingcyu** [comment]
Will add more information

**Comment by mingcyu** [comment]
@jantley-ibm Will send you email with the power point of the mock up from Alasdair. We will need to get license information from Marylin

**Comment by jantley-ibm** [comment]
@mingcyu see draft https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=installation-viewing-license-information

**Comment by mingcyu** [comment]
@jantley-ibm Looks good - thanks!

**Comment by jantley-ibm** [comment]
Thanks @mingcyu - closing
