### ISSUE TITLE
Install option using kubectl

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#97]
Provide install option using kubectl (along with curl and sed) similar to [OLO](https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/0.8.1/kubectl). Add it at internal/deploy/kubectl

**Comment by leochr** [comment]
@BradleyMayo please update the [kubectl install option PR](https://github.com/WASdev/websphere-liberty-operator/pull/154) to account for the recent updates to the operator artifacts (CRD, role/role binding, etc). Once you have updated it, send the information to @mtamboli and @tam512 so that it can be tested on non-OpenShift environment(s). 

Use the following operator image instead of `cp.stg.icr.io/cp/websphere-liberty-operator:main`. It's the operator controller image for the latest driver given to SVT:
`cp.stg.icr.io/cp/websphere-liberty-operator:b2b0f07db844e0b3970cfdf82f87a0ce330ee38f34df6926c09535b8ecbd2832`

fyi @mingcyu

**Comment by leochr** [comment]
@tam512 @mtamboli The install instructions (using kubectl/oc) are documented here. Please try and verify on non-OpenShift environment for all three install modes (watch own namespace, all namespaces/cluster, another namespace). Thanks.
https://github.com/WASdev/websphere-liberty-operator/tree/main/internal/deploy/kubectl

**Comment by tam512** [comment]
I verified the install instructions using kubectl on Azure Kubernetes cluster and it worked ok.  
The uninstall section should be updated to state that CR instance should be removed (_optional_) prior to uninstalling operator
